# Generated by Django 4.2 on 2025-11-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('director_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
