# Generated by Django 4.2 on 2025-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
